# Generated by Django 3.2 on 2022-03-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='email',
            field=models.EmailField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
